on:
  push:
    branches:
      - dev

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup release-please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
        if: ${{ steps.release.outputs.release_created }}
      - run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
      - name: Build
        run: echo "Build"
        if: ${{ steps.release.outputs.release_created }}
      - name: Deploy
        run: echo "Deploy"
        if: ${{ steps.release.outputs.release_created }}
